"""
Listor
Tuples
Dictionaries
Sets
"""

like = []
dislike = []
dishes = [
    "Spaghetti Carbonara",
    "Chicken Tikka Masala",
    "Sushi",
    "Hamburger",
    "Pad Thai",
    "Lasagna",
    "Chicken Alfredo",
    "Tacos",
    "Pizza",
    "Ramen",
    "Biryani",
    "Moussaka",
    "Steak",
    "Shrimp Scampi",
    "Fettuccine Alfredo",
    "Pasta Primavera",
    "Tom Yum Soup",
    "Pho",
    "Beef Stroganoff",
    "Ceviche",
    "Chili Con Carne",
    "Croissant",
    "Dim Sum",
    "Eggplant Parmesan",
    "Falafel",
    "Gnocchi",
    "Hummus",
    "Jambalaya",
    "Kebab",
    "Lemon Chicken",
    "Macaroni and Cheese",
    "Naan Bread",
    "Omelette",
    "Paella",
    "Quiche",
    "Ratatouille",
    "Sashimi",
    "Tiramisu",
    "Udon Noodles",
    "Vindaloo",
    "Wonton Soup",
    "Xiao Long Bao",
    "Yakitori",
    "Ziti",
    "Avocado Toast",
    "Banana Bread",
    "Cobb Salad",
    "Doner Kebab",
    "Eggs Benedict",
    "French Toast",
    "Goulash",
    "Hot Pot",
    "Ice Cream Sundae",
    "Jerk Chicken",
    "Katsu Curry",
    "Lamb Kofta",
    "Miso Soup",
    "Nicoise Salad",
    "Oysters Rockefeller",
    "Pancakes",
    "Quesadilla",
    "Risotto",
    "Samosa",
    "Tandoori Chicken",
    "Ube Ice Cream",
    "Veggie Burger",
    "Waffle",
    "Xacuti",
    "Yakisoba",
    "Zucchini Fritters",
    "Arancini",
    "Baklava",
    "Cannoli",
    "Dumplings",
    "Empanadas",
    "Fajitas",
    "Gazpacho",
    "Huevos Rancheros",
    "Iced Tea",
    "Jollof Rice",
    "Kung Pao Chicken",
    "Lobster Bisque",
    "Moules Frites",
    "Nasi Goreng",
    "Osso Buco",
    "Peking Duck",
    "Quinoa Salad",
    "Ramen Burger",
    "Samosa Chaat",
    "Tiramisu",
    "Udon Soup",
    "Vegan Pad Thai",
    "Waldorf Salad",
    "Xinjiang Lamb Skewers",
    "Yakitori Don",
    "Zucchini Noodles",
]


# Loopa igenom listan dishes och fråga användaren om de gillar maträtten eller inte
# Spara svaret i en variabel
# Om användaren gillar maträtten, lägg till den i listan like
# Om användaren inte gillar maträtten, lägg till den i listan dislike
# Om anvädanren skriver quit, avsluta programmet och skriv ut listorna like och dislike
